name: ExtendedGenerators
version: 1.0.0
api-version: 1.20
main: lu.kbra.extended_generators.ExtendedGenerators
author: UnKabaraQuiDev@github.com
commands:
  gengive:
    permission: op
  home:
    name: home
  sethome:
    name: sethome
  delhome:
    name: delhome
  homes:
    name: homes