name: ExtendedGenerators
version: 1.0.0
api-version: 1.20
main: lu.kbra.extended_generators.ExtendedGenerators
author: UnKabaraQuiDev@github.com
# depend: [ProtocolLib]
commands:
  island:
    name: "island"
    aliases: ["is"]
  clearconfig:
    name: "clearconfig"
    permission: op
  reloadconfig:
    name: "reloadconfig"
    permission: op
  saveconfig:
    name: "saveconfig"
    permission: op
  configisland:
    name: "configisland"
    aliases: ["cis"]
  superconfigisland:
    name: "superconfigisland"
    permission: op
    aliases: ["s_cis"]
  confineisland:
    name: "confineisland"
    aliases: ["confineis"]
    permission: op
  confinehome:
    name: "confinehome"
    aliases: ["confineh"]
    permission: op
  home:
    name: "home"
    aliases: ["h"]
  homes:
    name: "homes"
    aliases: ["hs"]
  sethome:
    name: "sethome"
    aliases: ["sh"]
  delhome:
    name: "delhome"
    aliases: ["dh"]
  superhome:
    name: "superhome"
    aliases: ["s_h"]
    permission: op
  superhomes:
    name: "superhomes"
    aliases: ["s_hs"]
    permission: op
  supersethome:
    name: "supersethome"
    aliases: ["s_sh"]
    permission: op
  superdelhome:
    name: "superdelhome"
    aliases: ["s_dh"]
    permission: op
  genstats:
    name: "genstats"